### ISSUE TITLE
can not compute in parallel

### ISSUE THREAD

**Issue by chunmeifeng** [wavefrontshaping/complexPyTorch#12]
Dear author, the current version can not compute in parallel, could you pls revise it ?

**Comment by chunmeifeng** [comment]
It seems the complexbatchnorm couldnot compute in parallel

**Comment by wavefrontshaping** [comment]
I cannot help you if you are not willing to share a minimum amount of relevant information.
Can you please at least tell what you did, what is the error, and provide a **minimal reproducible example** to reproduce the error?

**Comment by wavefrontshaping** [comment]
Not enough information.
