### ISSUE TITLE
ConvTranspose2d error 

### ISSUE THREAD

**Issue by Dub21** [wavefrontshaping/complexPyTorch#14]
Hello, thanks for your work. I am trying to use it for image to image translation but I got the following error while using the ConvTranspose2d error : RuntimeError: Input type (CUDAComplexFloatType) and weight type (torch.cuda.FloatTensor) should be the same
Have you been able to successfully use ConvTranspose2d?

Thanks

**Comment by wavefrontshaping** [comment]
Hi, 
Can you please provide a minimal example to reproduce the error?
Thx

**Comment by Dub21** [comment]
class ComplexNet_Unet(nn.Module):
    
    def __init__(self):
        super(ComplexNet_Unet, self).__init__()
        self.conv1 = ComplexConv2d(1, 8, 5, 2, 2)
        #self.bn1  = ComplexBatchNorm2d(8)
        self.conv2 = ComplexConv2d(8, 8, 5, 2, 2)
        self.bn2  = ComplexBatchNorm2d(8)
        self.conv3 = ComplexConv2d(8, 16, 5, 2, 2)
        self.bn3  = ComplexBatchNorm2d(16)
        self.conv4= ComplexConv2d(16, 32, 5, 2, 2)
        self.bn4  = ComplexBatchNorm2d(32)
        self.conv5= ComplexConv2d(32, 64, 5, 2, 2)
        self.bn5  = ComplexBatchNorm2d(64)

        self.conv6= ComplexConv2d(64, 128, 5, 1, 2)
        
        self.conv7= ConvTranspose2d(128, 64, 1,1)
        self.bn7  = ComplexBatchNorm2d(64)
        self.conv8= ConvTranspose2d(64, 32, 1, 1)
        self.bn8  = ComplexBatchNorm2d(32)
        self.conv9= ConvTranspose2d(32, 16, 1, 1)
        self.bn9  = ComplexBatchNorm2d(16)
        self.conv10= ConvTranspose2d(16, 8, 1, 1)
        self.bn10  = ComplexBatchNorm2d(8)
        self.conv11= ComplexConv2d(8, 1, 5, 1, 1)



        #self.bn3  = ComplexBatchNorm2d(16)
        #self.conv5= ComplexConv2d(16, 8, 5, 1,2)
        #self.bn4  = ComplexBatchNorm2d(8)
        #self.conv6= ComplexConv2d(8, 1, 5, 1,2)

        '''
        self.trans1 = ConvTranspose2d(16, 8, 1,1,0,0,1,True,1, padding_mode='zeros')
        self.bn3  = ComplexBatchNorm2d(8)
        self.trans2 = ConvTranspose2d(8, 4, 1,1)
        self.bn4  = ComplexBatchNorm2d(4)
        self.trans3 = ConvTranspose2d(4, 1, 1,1)
        self.bn5  = ComplexBatchNorm2d(1)
        self.conv4 = ComplexConv2d(1, 1, 5, 1,1)
'''

        #self.trans = ComplexConvTranspose2d()
        #self.fc1 = ComplexLinear(4*4*20, 500)
        #self.fc2 = ComplexLinear(500, 10)
             
    def forward(self,x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.bn2(x)
        x = complex_relu(x)
        x = self.conv3(x)
        x = self.bn3(x)
        x = complex_relu(x)
        x = self.conv4(x)
        x = self.bn4(x)
        x = complex_relu(x)
        x = self.conv5(x)
        x = self.bn5(x)
        x = complex_relu(x)

        x = self.conv6(x)

        x = complex_upsample(x, scale_factor=2)
        x = self.conv7(x)
        x = self.bn7(x)
        x = complex_relu(x)
        x = complex_upsample(x, scale_factor=2)
        x = self.conv8(x)
        x = self.bn8(x)
        x = complex_relu(x)
        x = complex_upsample(x, scale_factor=2)
        x = self.conv9(x)
        x = self.bn9(x)
        x = complex_relu(x)
        x = complex_upsample(x, scale_factor=2)
        x = self.conv10(x)
        x = self.bn10(x)
        x = complex_relu(x)
        x = complex_upsample(x, scale_factor=2)
        x = self.conv11(x)
        #x = complex_upsample(x, scale_factor=2)


        '''
        x = self.bn3(x)
        x = complex_relu(x)
        x = self.conv5(x)
        x = self.bn4(x)
        x = complex_relu(x)
        x = self.conv6(x)
        '''
        #x = complex_relu(x)
        #x = self.trans2(x)
       # x = self.bn4(x)
       # x = self.trans3(x)
       # x = self.bn4(x)
        #x = self.conv4(x)
        return x
    
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = ComplexNet_Unet().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)loss = nn.L1Loss()

def train(model, device, data,target, optimizer, epochs):
    model.train()
    for epoch in range(epochs):

        #data = torch.complex(torch.DoubleTensor(np.real(X)),torch.DoubleTensor(np.imag(X)))
        #target = torch.complex(torch.DoubleTensor(np.real(y)),torch.DoubleTensor(np.imag(y)))

        #data, target = data2.to(device).type(torch.complex64), target2.to(device)
        optimizer.zero_grad()
        output = model(data)
        print(output.shape)
        value = loss(output, target)
        print(value)
        value.backward()
        optimizer.step()
        if batch_idx % 100 == 0:
            print('Train Epoch: {:3} [{:6}/{:6} ({:3.0f}%)]\tLoss: {:.6f}'.format(
                epoch,
                batch_idx * len(data), 
                len(train_loader.dataset),
                100. * batch_idx / len(train_loader), 
                loss.item())
            )

# Run training on 50 epochs
for epoch in range(1):
    train(model, device, data, target, optimizer, 500)

**Comment by wavefrontshaping** [comment]
Before testing anything, I see that you use the native `ConvTranspose2d` instead of the complex counterpart `ComplexConvTranspose2d` from *complexPyTorch*. Is that on purpose?
