### ISSUE TITLE
A bug in ComplexBatchNorm1d

### ISSUE THREAD

**Issue by yuzhiyang123** [wavefrontshaping/complexPyTorch#16]
In line 301 of ComplexLayers.py, it should be "input = input - mean[None, :]" instead of "input = input - mean[None, :, None, None]" since the input of ComplexBatchNorm1d only has 2 or 3 dimensions.

**Comment by wavefrontshaping** [comment]
Corrected, I replaced by `input = input - mean[None, ...]`

Thanks for notifying the error
