### ISSUE TITLE
About operating efficiency and convergence

### ISSUE THREAD

**Issue by echocatzh** [wavefrontshaping/complexPyTorch#22]
I found some problems when using **ComplexGRUCell**
a. the complex-valued operator runs much lower than the real-valued operator, using such a complex-valued structure is much slower
b. the convergence may not be easily controlled, is there any paper supporting the point like complex-valued RNN is better than real-valued RNN in specific cases?

**Comment by wavefrontshaping** [comment]
complexPyTorch is deprecated as PyTorch now natively supports complex values. You are better of using standard modules.

**Comment by echocatzh** [comment]
thx for your advice.
