### ISSUE TITLE
How to use kernel for 1D signal 

### ISSUE THREAD

**Issue by valavakilian** [wavefrontshaping/complexPyTorch#4]
Hello and thanks a lot for your repo.
I am trying to have a complex model which uses complex 1D signals  The size of the signals is 1024 for each real and complex signal separately. I separate real and imaginary and reshape the signals to [1,1,1,1024] but naturally I cannot use kernel size of size larger than 1. Normally I used conv1d for this signal (with the normal pytorch repository) but this repo does not yet support conv1d. 
My request is: I wanted to see if you have any suggested solutions or simple changes that I can make to accommodate 1d convolutions or somehow use the current 2d convolutions to do the trick .
Thank you

**Comment by drydenwiebe** [comment]
Hello,

It may be possible to use Conv2D where you specify a rectangular kernel of width 1.

**Comment by valavakilian** [comment]
Thanks I figured.
