### ISSUE TITLE
complex batch norm2d track_running_stats=False produce error

### ISSUE THREAD

**Issue by nisanaryal** [wavefrontshaping/complexPyTorch#6]
(1 - exponential_average_factor) * self.running_mean
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

There is a bug in batch normalization, when we initialize with track_running_stats=False , the parameters arent initialized(as expected) but in training it tries to update running mean and running covariance.

error occurs at this line
self.running_mean = exponential_average_factor * mean \
                                    + (1 - exponential_average_factor) * self.running_mean 
I think we need to keep this inside the loop checking the status of track_running_stats. And might have to change while self.training is false as well(havent checked this though).

**Comment by wavefrontshaping** [comment]
Indeed, track_running_stats was not checked correctly for eval mode.
Should be good now.
